name: Question
description: Ask a question about using QuizBot
labels: ["question"]
body:
  - type: textarea
    id: question
    attributes:
      label: Your question
      description: What would you like to know?
    validations:
      required: true
