"""add password column to quizzes

Revision ID: 87f3972b86f9
Revises: c7c8b196a8ef
Create Date: 2026-03-20 19:24:58.629391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87f3972b86f9'
down_revision: Union[str, Sequence[str], None] = 'c7c8b196a8ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quizzes', sa.Column('password', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quizzes', 'password')
    # ### end Alembic commands ###
