"""add persistence tables

Revision ID: c7c8b196a8ef
Revises: fac614386af2
Create Date: 2026-03-20 19:07:48.438272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7c8b196a8ef'
down_revision: Union[str, Sequence[str], None] = 'fac614386af2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('handler_name', sa.String(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('handler_name', 'chat_id', 'user_id')
    )
    op.create_index(op.f('ix_conversation_states_handler_name'), 'conversation_states', ['handler_name'], unique=False)
    op.create_table('user_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.LargeBinary(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_data_user_id'), 'user_data', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_data_user_id'), table_name='user_data')
    op.drop_table('user_data')
    op.drop_index(op.f('ix_conversation_states_handler_name'), table_name='conversation_states')
    op.drop_table('conversation_states')
    # ### end Alembic commands ###
